### ISSUE TITLE
AbstractPrimePageTest: Add browser console assertion and printing

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-selenium#3]
Add ability to assert there are no JavaScript console errors as well a print the current messages in the console.

SEVERE messages to `System.err`
OTHER messages to `System.out` will be useful for debugging.

**Comment by tandraschko** [comment]
Please dont add the final Keyword to params :P @

**Comment by melloware** [comment]
Sorry IntelliJ added that i just fixed it.

**Comment by melloware** [comment]
Damn the Gecko driver doesn't support console logs yet.  I have subscribed to this thread as is a very popular feature request.

https://github.com/mozilla/geckodriver/issues/284

**Comment by melloware** [comment]
I fixed this so it will run and assert if using Chrome and do nothing if running in Firefox.
