### ISSUE TITLE
Doc: How to create component without annotations

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-selenium#61]
Based on this forum post: https://forum.primefaces.org/viewtopic.php?f=3&t=45459

Answer was to do:
```java
PrimePageFragmentFactory.create(SelectBooleanCheckbox.class, Driver.findElement(By.id("")));
```

I am wondering whether we should make a shortcut method to this in `PrimeSelenium` like...

```java
PrimeSelenium.create(SelectBooleanCheckbox.class, Driver.findElement(By.id("")));
```

Or should I just add the first one to the README.MD and be done with it?

**Comment by tandraschko** [comment]
please test it before :D 
and yes, a shortcut would be better in PrimeSelenium
maybe 2 variations: 1 with the source element, 1 with a selector

**Comment by melloware** [comment]
OK good idea.

**Comment by tandraschko** [comment]
do you work on it? otherwise i would do it now

**Comment by tandraschko** [comment]
primefaces-selenium doesnt compile anymore on my machine.
Violations also present in 21 other files.
Run 'mvn spotless:apply' to fix these violations.

what is spotless plugin and why we added it?

**Comment by tandraschko** [comment]
it seems like a formatter plugin, TBH i dont like that stuff
same like PMD and so on, its also to strict
checkstyle is enough IMO if you have code reviews

please also talk with other commiters next time when you introduce something.

**Comment by melloware** [comment]
Spotless keeps the code spotless and formatted perfectly regadless of Netbeans, Eclipse ,IntelliJ or whatever IDe you use.  and mvn spotless:apply fixes the formatting of the whole project.

it also makes sure your Netbeans doens't mess up the Line endings :)

**Comment by melloware** [comment]
And yes I have a fix right now just testing it.

**Comment by tandraschko** [comment]
No plugin found for prefix 'spotless' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Andraschko\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]****


sorry but thats not fun :P i checkout the project, compile doesnt work because of warnings of a plugin, which never was discussed and i cant even run the plugin via mvn spotless:apply

**Comment by melloware** [comment]
I don't know why its the most popular plugin and all of the Apache Commons projects have moved to it.  Sounds like you have a problem locally as @christophs78 and I have been adding components for months here with no issues.

**Comment by melloware** [comment]
And our Automated build runs so it clearly finds the Spotless plugin in Maven Central.

**Comment by melloware** [comment]
I can remove Spotless but I got the idea for Spotless from @rmannibucau Romain Manni-Bucau who stated:
"Spotless is also used by the ASF and avoids issues, ran by default or not so I think it is saner."

**Comment by tandraschko** [comment]
Its related to NetBeans because it checkout with `\n` probably
works fine with clone via cmd
its not cool that such a plugin makes a whole IDE for me unusable :P

**Comment by tandraschko** [comment]
that damn Romain @rmannibucau :PP :D sry :)

**Comment by melloware** [comment]
Eventually you just have to abandon Netbeans :)

**Comment by rmannibucau** [comment]
Hehe, the story behind spotless is that it is more or less the same than formatter plugin without the dependency on p2 repo (it is plain central there) so it behaves between and reduces latency and is deterministic. So between both spotless is saner for sure.

About netbeans I would just tune its git config before moving to vscode or idea ;).

**Comment by tandraschko** [comment]
yep, sounds good :)

@melloware shouldnt we name the method something like createFragement? create might be to broad

**Comment by melloware** [comment]
`creatComponent` or `createFragment` ?

**Comment by melloware** [comment]
OK I do like `createFragment` better. Fixing now.

**Comment by melloware** [comment]
OK checked in update to `createFragment`!
