### ISSUE TITLE
DatePicker/Calendar: TimeZone Handling

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-selenium#7]
As reported by @christophs78 we need to figure out the proper way to get and send dates to/from the browser in the appropriate timezone.

**Comment by markuung** [comment]
What exactly do you mean by "timezone handling"? DatePicker and Calendar already somewhat deal with converting timezones to reach the same input/output behaviour as the browser - except for DatePicker#getValueAsLocalDate(), which produces incorrect results for me.
The time doesn't get aligned with the timezone offset there and therefore can produce a wrong date.

**Comment by melloware** [comment]
@markuung The code is doing the following:
```java
 public LocalDate getValueAsLocalDate() {
        Object date = PrimeSelenium.executeScript("return " + getWidgetByIdScript() + ".getDate()");

        if (date == null) {
            return null;
        }

        String utcTimeString = PrimeSelenium.executeScript("return " + getWidgetByIdScript() + ".getDate().toUTCString();");
        return LocalDate.parse(utcTimeString, DateTimeFormatter.RFC_1123_DATE_TIME);
    }
```

Its getting the Date from the Browser calling `toUTCString` to string and make it a UTC date.  However when LocalDate.parse that UTC Time String it contains the browser's timezone offset so its producing and incorrect date when trying to translate from browser to server side date.

**Comment by markuung** [comment]
@melloware This is exactly what I described by the time not being aligned to the correct timezone. DatePicker#getValue() is already dealing with this issue, and should return a LocalDateTime aligned to the browser (and system) timezone. I'd just reuse it and replace DatePicker#getValueAsLocalDate() with something like this:
```java
public LocalDate getValueAsLocalDate() {
    LocalDateTime value = getValue();

    return value != null ? value.toLocalDate() : null;
}
```

I was not sure if you meant something else by "timezone handling"

**Comment by melloware** [comment]
Nope that is perfect thanks for the recommendation I will fix it tomorrow!
